---
title: "Winter_data_analysis"
author: "Anna Di Natale"
date: "2023-12-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Loading required libraries
```{r}
library(jsonlite)
library(dplyr)

```

Loading data
```{r}
winter_data<-read.csv('C:\\Users\\dinata01\\Documents\\DirSem\\Winter-2022-98.tsv',sep='\t') ##data about over marking from Winter
ground_truth<-read.csv('C:\\Users\\dinata01\\Documents\\DirSem\\ground_truth_Winter.csv',sep=';')  ##data about linguistic change from Urban
```

Restructuring data in a proper dataframe
```{r}

winter_df<-data.frame(stringsAsFactors = F) ##initialising dataframe

for (i in seq (1,nrow(winter_data))) ##loop on imported data
{
  concept<-winter_data$ENGLISH[i]
  ##ordering sources
  sources<-fromJSON(winter_data$SOURCE_CONCEPTS[i])
  for(j in seq(1,nrow(sources)))
  {
    source<-sources$name[j]
    df<-data.frame(source=source,target=concept,polysemy=sources$polysemy[j],
               overt_marking=sources$overt_marking[j],stringsAsFactors = F)
    winter_df<-rbind(winter_df,df)
  }
  ##ordering targets
  targets<-fromJSON(winter_data$TARGET_CONCEPTS[i])
    for(j in seq(1,nrow(targets)))
  {
    target<-targets$name[j]
    df<-data.frame(source=concept,target=target,polysemy=targets$polysemy[j],
               overt_marking=targets$overt_marking[j],stringsAsFactors = F)
    winter_df<-rbind(winter_df,df)
  }
}
winter_df<-winter_df[-which(duplicated(winter_df)),] ##removing duplicates
rownames(winter_df)<-seq(1,nrow(winter_df)) ##renaming rows

winter_df<-winter_df[-which(winter_df$source=='day'&winter_df$target=='noon'),] ##removing because of error in the data
```

Merging Winter data with ground truth
```{r}
merged_df<-left_join(ground_truth,winter_df) ##merging data for overt marking
merged_df<-left_join(merged_df,winter_df,by=c("source"="target","target"="source")) ##adding opposite overt marking
merged_df$polysemy.y<-NULL ##removing duplicate column
merged_df<-merged_df%>%rename("opposite_overt_marking"="overt_marking.y") ##renaming column

test<-full_join(ground_truth[ground_truth$correlation==1,],ground_truth[ground_truth$correlation==0,],by=c("source"="target","target"="source"))
```


